### ISSUE TITLE
[Question] - Source of data you use

### ISSUE THREAD

**Issue by emirozer** [pivotal-cf-experimental/datadog-config-oss#4]
Hey ,

First, thanks for sharing your dashboards, looks great for monitoring a cf cluster. Now i do know that you use it to monitor pws itself. I was working on to making it work for a standart cloudfoundry cluster.
But i have a question, for the source of data do you deploy https://github.com/cloudfoundry-incubator/datadog-firehose-nozzle ? Or you gather data from diego ? What are the data sources that you feed datadog with?

Thanks,

Emir

**Comment by pronoiac** [comment]
Yes, we use the firehose nozzle.
